SELECT
    j.JobID,
    j.EmailID,
    j.AccountID,
    j.AccountUserId,
    j.FromName,
    j.FromEmail,
    j.SchedTime,
    j.PickupTime,
    j.DeliveredTime,
    j.EventID,
    j.IsMultipart,
    j.JobType,
    j.JobStatus,
    j.ModifiedBy,
    j.ModifiedDate,
    j.EmailName,
    j.EmailSubject,
    j.IsWrapped,
    j.TestEmailAddr,
    j.Category,
    j.BccEmail,
    j.OriginalSchedTime,
    j.CreatedDate,
    j.CharacterSet,
    j.IPAddress,
    j.SalesForceTotalSubscriberCount,
    j.SalesforceErrorSubscriberCOunt,
    j.SendType,
    j.DynamicEmailSubject,
    j.SuppressTracking,
    j.SendClassificationType,
    j.SendClassification,
    j.ResolveLinksWithCurrentData,
    j.EmailSendDefinition,
    j.DeduplicateByEmail,
    s.TriggererSendDefinitionObjectID,
    s.TriggeredSendCustomerKey,
    s.ListID,
    s.BatchID,
    s.SubscriberID,
    s.SubscriberKey,
    s.EventDate,
    sub.EmailAddress,
    sub.Status,
    sub.CreatedDate SubCreatedDate
FROM
    _Sent s
    LEFT JOIN _Job j ON s.JobID = j.JobID
    LEFT JOIN ENT._ListSubscribers Sub ON s.SubscriberID = sub.SubscriberID
WHERE
    s.EventDate >= DATEADD(DAY, -11, GETDATE())
